# OpenWeather API Configuration
[openweather]
api_key = "68d5a17a506d6845fc419a5089e88934"

# You can get a free API key from: https://openweathermap.org/api
# Replace YOUR_OPENWEATHER_API_KEY_HERE with your actual API key

# Email Alert Configuration
[email]
enabled = true  # Set to true to enable email alerts
smtp_server = "smtp.gmail.com"  # Gmail SMTP server
smtp_port = 587
sender_email = "it21737002@matrusri.edu.in"  # Your Gmail address
sender_password = "ctfr tszv cqja qfqz"  # Your Gmail app password (not regular password)
admin_email = "pranathisimhadri1@gmail.com"  # Admin email to receive alerts

# For Gmail:
# 1. Enable 2-factor authentication
# 2. Generate an "App Password" in your Google Account settings
# 3. Use the app password here, not your regular Gmail password
# 4. Set enabled = true to activate email alerts
